spring:
  application:
    name: black-ai

  datasource:
    url: jdbc:mysql://localhost:3306/black_ai?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
  
  vector-datasource:
    url: jdbc:postgresql://localhost:5432/blackai_db
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  ai:
    ollama:
      embedding:
        options:
          model: bge-m3
      base-url: http://localhost:11434
      chat:
        options:
          model: gemma4:e4b
      
    # vectorstore:
    #   pgvector:
    #     index-type: HNSW
    #     distance-type: COSINE_DISTANCE
    #     dimensions: 1024
    # 메모리 vectorStore에서 pgvector로 변경하며 직접 bean 설정
      

logging:
  level:
    org.springframework: INFO